# Generated by Django 3.2.16 on 2023-04-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post']},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-user']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-author']},
        ),
    ]
